export const lessons = [
  {
    name: 'Ribbon banner',
    folder: 'ribbon',
    language: 'HTML',
    image: '/images/thumbnails/ribbon.jpg',
    duration: '15 minutes',
    difficulty: 'mild',
  },
  {
    name: 'Background split',
    folder: 'background-split',
    language: 'HTML',
    image: '/images/thumbnails/background-split.jpg',
    duration: '30 minutes',
    difficulty: 'mild',
  },
  {
    name: 'Caret cutoff',
    folder: 'caret-cutoff',
    language: 'HTML',
    image: '/images/thumbnails/caret-cutoff.jpg',
    duration: '20 minutes',
    difficulty: 'spicy',
  },
  {
    name: 'Scrolling fade-out list',
    folder: 'scrolling-list',
    language: 'HTML',
    image: '/images/thumbnails/scroll-list.jpg',
    duration: '25 minutes',
    difficulty: 'mild',
  },
  {
    name: 'Animated stripes',
    folder: 'animated-stripes',
    language: 'HTML',
    image: '/images/thumbnails/animated-stripes.jpg',
    duration: '35 minutes',
    difficulty: 'hot',
  },
  {
    name: 'Slide-in confirmation',
    folder: 'slide-in-confirmation',
    language: 'JSX',
    image: '/images/thumbnails/slide-in-confirmation.jpg',
    duration: '33 minutes',
    difficulty: 'spicy',
  },
]
